DROP DATABASE IF EXISTS ubongoDB;
CREATE DATABASE ubongoDB;

USE ubongoDB;

CREATE TABLE Users(
  username VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL,
  PRIMARY KEY(username)
);
